### ISSUE TITLE
Request: Add a button to reset the search query

### ISSUE THREAD

**Issue by Protuhj** [JaroVDH/PoE-archnemesis-recipes#1]
If I type in filter text in Chrome, or Edge, a little 'x' gets added to the search box to clear the text out, but not in Firefox.

Can you add a reset button as a catch-all for resetting? 

(The 'x' also doesn't work in the Browser widget for Microsoft Gamebar, so the button would help in that case)

**Comment by JaroVDH** [comment]
That's how some browsers interpret the "search" type inputs and not something I specifically put in.

**Comment by Protuhj** [comment]
I know.. but what I'm asking for is an explicit reset button, since the behavior isn't consistent (or even exists) across browsers.
