### ISSUE TITLE
[Bug] Recipes using "Steel-infused" are broken

### ISSUE THREAD

**Issue by Protuhj** [JaroVDH/PoE-archnemesis-recipes#2]
You have the correct name for "Steel-infused" at https://github.com/JaroVDH/PoE-archnemesis-recipes/blob/main/view.js#L135 but then you reference it as `Steel-Infused`

At: 
- https://github.com/JaroVDH/PoE-archnemesis-recipes/blob/main/view.js#L295
- https://github.com/JaroVDH/PoE-archnemesis-recipes/blob/main/view.js#L337

Case-sensitivity seems to break it

**Comment by JaroVDH** [comment]
Fixed.
Thanks for letting me know!
