### ISSUE TITLE
The latest changes broke the page in the Browser Gamebar widget

### ISSUE THREAD

**Issue by Protuhj** [JaroVDH/PoE-archnemesis-recipes#3]
In the Browser widget for Gamebar (https://www.microsoft.com/en-us/p/browser-for-game-bar/9nk1cnb0nccx#activetab=pivot:overviewtab)

Your latest changes broke it. No idea what did it, but it worked before your latest commit.

Edit: This isn't to say the widget is a perfect JS engine, but still... it worked before, and now it doesn't.

**Comment by Protuhj** [comment]
This browser widget is too jank to worry about creating an issue to address it, I think.

**Comment by JaroVDH** [comment]
I might've fixed it just now. I used some optional chaining, but I forgot I didn't bother putting proper build tools in this.

**Comment by Protuhj** [comment]
Yeah, it seems to work again! Thanks!
